import requests
import os
import smtplib
import time
from email.mime.text import MIMEText
from email.header import Header
from datetime import datetime

def get_poly_data():
    """获取 Polymarket 赔率（纯英精修版）"""
    url = "https://gamma-api.polymarket.com/events?limit=10&active=true&closed=false"
    try:
        response = requests.get(url, timeout=15)
        data = response.json()
        report = "📊 POLYMARKET REAL-TIME ODDS\n"
        report += "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        
        for event in data:
            title = event.get('title', 'N/A')
            markets = event.get('markets', [{}])[0]
            group = markets.get('groupNames', ['Yes', 'No'])
            prices = markets.get('outcomePrices', ['0', '0'])
            
            # 格式化胜率：将 0.65 转换为更加直观的 65.0%
            try:
                p1 = f"{float(prices[0])*100:.1f}%" if prices else "0%"
                p2 = f"{float(prices[1])*100:.1f}%" if len(prices) > 1 else "0%"
                report += f"🔹 {title}\n"
                report += f"   PROBABILITY: {group[0]} ({p1}) vs {group[1]} ({p2})\n\n"
            except:
                continue
        return report
    except Exception as e:
        return f"❌ Polymarket Data Error: {e}\n"

def get_news_data():
    """获取全球前沿新闻（带摘要增强版）"""
    # 增加 pageSize 到 10，并尝试获取摘要
    url = "https://newsapi.org/v2/top-headlines?language=en&pageSize=10&apiKey=02392437e56847849e7550f28e67f08b"
    try:
        response = requests.get(url, timeout=15)
        articles = response.json().get('articles', [])
        report = "🌍 GLOBAL FRONTIER NEWS SUMMARY\n"
        report += "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        
        for i, art in enumerate(articles, 1):
            title = art.get('title', 'No Title')
            source = art.get('source', {}).get('name', 'Unknown')
            desc = art.get('description', 'No summary available.')
            
            report += f"{i}. {title}\n"
            report += f"   Source: {source}\n"
            # 只取简短摘要的前 100 个字符，保持排版整洁
            report += f"   Brief: {desc[:120]}...\n\n"
        return report
    except Exception as e:
        return "❌ News Data Error\n"

def send_email(content):
    mail_host = "smtp.qq.com"
    mail_user = os.getenv("MAIL_USER")
    mail_pass = os.getenv("MAIL_PASS")
    mail_receiver = os.getenv("MAIL_RECEIVER")

    if not all([mail_user, mail_pass, mail_receiver]):
        return False

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    message = MIMEText(content, 'plain', 'utf-8')
    message['From'] = f"M4_Intelligence_Bot <{mail_user}>"
    message['To'] = mail_receiver
    # 标题也换成高端的英文
    message['Subject'] = Header(f"Daily Intelligence Report | {now_str}", 'utf-8')

    try:
        smtp = smtplib.SMTP_SSL(mail_host, 465, timeout=15)
        smtp.login(mail_user, mail_pass)
        smtp.sendmail(mail_user, [mail_receiver], message.as_string())
        smtp.quit()
        print(f"✅ Report Sent: {now_str}")
        return True
    except Exception as e:
        print(f"❌ Send Failed: {e}")
        return False

if __name__ == "__main__":
    # 重新组合逻辑：新闻在上，赔率在下
    news_part = get_news_data()
    poly_part = get_poly_data()
    
    final_report = "PREMIUM DAILY INTELLIGENCE SUMMARY\n"
    final_report += "Generated by M4 Mac mini | " + datetime.now().strftime("%Y-%m-%d") + "\n"
    final_report += "━" * 40 + "\n\n"
    final_report += news_part + "\n"
    final_report += poly_part
    final_report += "\n[End of Report]"
    
    send_email(final_report)